- name: Update all packages to the latest version
  apt:
    upgrade: dist
    update_cache: yes

- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: no
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - ebtables
    - ethtool
    - jq
